services:
  - type: web
    name: cafe-finder-be
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
